image: synapsedev/gcc-arm-none-eabi

build_stm32f042f6:
  stage: build
  script:
    - cd firmware/firmware/fw-stm32f042
    - cmake -DCMAKE_TOOLCHAIN_FILE=STM32F042x6.cmake -DTARGET_CPU=STM32F042F6
    - make

build_stm32f042k6:
  stage: build
  script:
    - cd firmware/firmware/fw-stm32f042
    - cmake -DCMAKE_TOOLCHAIN_FILE=STM32F042x6.cmake -DTARGET_CPU=STM32F042F6
    - make
