version: 1.0.{build}
install:
- cmd: >-
    set QTDIR=C:\Qt\5.7\mingw53_32

    set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
build_script:
- cmd: >-
    cd gui

    qmake MeasurementTool.pro

    mingw32-make -j

    del release\*.cpp

    del release\*.o

    cp *.txt release\

artifacts:
- path: gui/release/MeasurementTool.exe
  name: MeasurementTool.exe
- path: gui/release
  name: MeasurementTool
